spring.application.name=motor-fraudes-api
# Configurações de conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_motor_fraudes
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate (JPA) para criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


