spring.application.name=motor-fraudes-api

# Configuracoes de conexao com o PostgreSQL na Nuvem (Neon)
spring.datasource.url=jdbc:postgresql://ep-aged-mud-aq6scauq.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0nZ9rRqYhMTj
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao do Hibernate (JPA) para criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
